chore: fix issue with missing playwright binaries in CI
`pnpx playwright install` was installing a different set of browsers, not the
ones expected by actually used playwright.

The error was:
  Error: Executable doesn't exist at
  /home/runner/.cache/ms-playwright/chromium-1067/chrome-linux/chrome
  Looks like Playwright Test or Playwright was just installed or updated.